import { Router, type IRouter } from "express";
import pricingRouter from "./pricing";
import authRouter from "./auth";
import paymentRouter from "./payment";
import tenantRouter from "./tenant";
import subscriptionRouter from "./subscription";
import billingRouter from "./billing";
import onboardingRouter from "./onboarding";
import adminRouter from "./admin";
import customersRouter from "./customers";
import quotesRouter from "./quotes";
import jobsRouter from "./jobs";
import fleetRouter from "./fleet";
import complianceRouter from "./compliance";
import teamRouter from "./team";
import dashboardRouter from "./dashboard";
import posRouter from "./pos";
import posCatalogRouter from "./posCatalog";
import invoicesRouter from "./invoices";
import invoiceTemplatesRouter from "./invoiceTemplates";
import leadsRouter from "./leads";
import portalRouter from "./portal";
import invitationsRouter from "./invitations";
import storageRouter from "./storage";
import filesRouter from "./files";
import brandingRouter from "./branding";
import usageRouter from "./usage";
import adminWorkersRouter from "./adminWorkers";
import inboxRouter from "./inbox";
import notificationsRouter from "./notifications";
import partnerRouter from "./partner";
import adminReferralsRouter from "./adminReferrals";
import tenantReferralsRouter from "./tenantReferrals";
import marketplaceRouter from "./marketplace";
import whiteLabelRouter from "./whiteLabel";
import reportsRouter from "./reports";
import integrationsRouter from "./integrations";
import automationRouter from "./automation";
import aiRouter from "./ai";
import voiceRouter from "./voice";
import timesheetsRouter from "./timesheets";
import contractsRouter from "./contracts";
import staffAvailabilityRouter from "./staffAvailability";

const router: IRouter = Router();

router.get("/v1/health", (_req, res) => {
  res.json({ status: "ok" });
});
router.get("/healthz", (_req, res) => {
  res.json({ status: "ok" });
});

router.use(pricingRouter);
router.use(authRouter);
router.use(paymentRouter);
router.use(tenantRouter);
router.use(subscriptionRouter);
router.use(billingRouter);
router.use(onboardingRouter);
router.use(leadsRouter);
router.use(adminRouter);
router.use(customersRouter);
router.use(quotesRouter);
router.use(jobsRouter);
router.use(fleetRouter);
router.use(complianceRouter);
router.use(teamRouter);
router.use(dashboardRouter);
router.use(posRouter);
router.use(posCatalogRouter);
router.use(invoicesRouter);
router.use(invoiceTemplatesRouter);
router.use(portalRouter);
router.use(invitationsRouter);
router.use(storageRouter);
router.use(filesRouter);
router.use(brandingRouter);
router.use(usageRouter);
router.use(adminWorkersRouter);
router.use(inboxRouter);
router.use(notificationsRouter);
router.use(partnerRouter);
router.use(adminReferralsRouter);
router.use(tenantReferralsRouter);
router.use(marketplaceRouter);
router.use(whiteLabelRouter);
router.use(reportsRouter);
router.use(integrationsRouter);
router.use(automationRouter);
router.use(aiRouter);
router.use(voiceRouter);
router.use(timesheetsRouter);
router.use(contractsRouter);
router.use(staffAvailabilityRouter);

export default router;
